export const PAYMENT_STATUS = {
  PENDING: "PENDING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED"
};

export const PAYMENT_METHOD = {
  CARD: "CARD",
  WALLET: "WALLET",
  BANK_TRANSFER: "BANK_TRANSFER"
};
